# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/pos_lite_myanmar?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Yangon
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER
# ===============================
server.port=8080
server.address=0.0.0.0

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET:a9f3Kx7@Lm2@Qz8!vN6pRt5$uY1sWc4Hd}
jwt.expiration=${JWT_EXPIRATION:86400000}

# ===============================
# CORS (for React Native)
# ===============================
cors.allowed-origins=http://localhost:19000,http://localhost:8081,http://10.0.2.2:19000,exp://localhost:19000,exp://10.0.2.2:19000
